import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { z } from "zod";
import { renderSchema } from "../../src/server/engine/runner.ts";
import {
  BuildEnvelope,
  DocumentEnvelope,
  PlanEnvelope,
  ReviewEnvelope,
  ScoutEnvelope,
  ShipEnvelope,
} from "../../src/starter-kit/envelopes.ts";

/**
 * Schema-render equivalence: the human/prompt rendering of each starter
 * envelope must be byte-identical to the frozen baseline captured before the
 * `_def`-cast removal. The fixtures are the independent source of truth — they
 * were generated by the pre-refactor renderSchema, so any drift in the new
 * introspection path fails here.
 */

const cases: [string, z.ZodTypeAny][] = [
  ["Plan", PlanEnvelope],
  ["Build", BuildEnvelope],
  ["Scout", ScoutEnvelope],
  ["Review", ReviewEnvelope],
  ["Document", DocumentEnvelope],
  ["Ship", ShipEnvelope],
];

for (const [name, schema] of cases) {
  test(`renderSchema output for ${name} envelope is unchanged`, () => {
    const expected = readFileSync(join(import.meta.dir, "fixtures/schema-render", `${name}.txt`), "utf8");
    expect(renderSchema(schema)).toBe(expected);
  });
}
